
const elements = {
    "hidrogenio": {
        symbol: "H",
        name: "Hidrogênio",
        category: "hidrogenio",
        atomic_number: 1,
        atomic_mass: 1.008,
    },
    "helio": {
        symbol: "He",
        name: "Hélio",
        category: "gas_nobre",
        atomic_number: 2,
        atomic_mass: 4.0026,
    },
    "litio": {
        symbol: "Li",
        name: "Lítio",
        category: "metal_alcalino",
        atomic_number: 3,
        atomic_mass: 6.94,
    },
    "carbono": {
        symbol: "C",
        name: "Carbono",
        category: "ametal",
        atomic_number: 6,
        atomic_mass: 12.011,
    },
    "nitrogenio": {
        symbol: "N",
        name: "Nitrogênio",
        category: "ametal",
        atomic_number: 7,
        atomic_mass: 14.007,
    },
    "oxigenio": {
        symbol: "O",
        name: "Oxigênio",
        category: "ametal",
        atomic_number: 8,
        atomic_mass: 15.999,
    },
    "fluor": {
        symbol: "F",
        name: "Flúor",
        category: "halogenio",
        atomic_number: 9,
        atomic_mass: 18.998,
    },
    "sodio": {
        symbol: "Na",
        name: "Sódio",
        category: "metal_alcalino",
        atomic_number: 11,
        atomic_mass: 22.989,
    },
    "magnesio": {
        symbol: "Mg",
        name: "Magnésio",
        category: "metal_alcalino_terroso",
        atomic_number: 12,
        atomic_mass: 24.305,
    },
    "aluminio": {
        symbol: "Al",
        name: "Alumínio",
        category: "metal_representativo",
        atomic_number: 13,
        atomic_mass: 26.981,
    },
    "fosforo": {
        symbol: "P",
        name: "Fósforo",
        category: "ametal",
        atomic_number: 15,
        atomic_mass: 30.974,
    },
    "enxofre": {
        symbol: "S",
        name: "Enxofre",
        category: "ametal",
        atomic_number: 16,
        atomic_mass: 32.06,
    },
    "cloro": {
        symbol: "Cl",
        name: "Cloro",
        category: "halogenio",
        atomic_number: 17,
        atomic_mass: 35.45,
    },
    "ferro": {
        symbol: "Fe",
        name: "Ferro",
        category: "metal_de_transicao",
        atomic_number: 26,
        atomic_mass: 55.845,
    },
    "niquel": {
        symbol: "Ni",
        name: "Níquel",
        category: "metal_de_transicao",
        atomic_number: 28,
        atomic_mass: 58.693,
    },
    "cobre": {
        symbol: "Cu",
        name: "Cobre",
        category: "metal_de_transicao",
        atomic_number: 29,
        atomic_mass: 63.546,
    },
    "ouro": {
        symbol: "Au",
        name: "Ouro",
        category: "metal_de_transicao",
        atomic_number: 79,
        atomic_mass: 196.967,
    },
    "uranio": {
        symbol: "U",
        name: "Urânio",
        category: "actinideo",
        atomic_number: 92,
        atomic_mass: 238.029,
    },
    "arsenio": {
        symbol: "As",
        name: "Arsênio",
        category: "semimetal",
        atomic_number: 33,
        atomic_mass: 74.922,
    }
}
